Repository afc163/fanyi, pull requests merged in 2024-09, with the labels that each got.

#102 chore: add biome and github action
  .github/dependabot.yml
  .github/workflows/test.yml
  .gitignore
  .prettierrc
  .travis.yml
  _config.yml
  bin/fanyi.js
  biome.json
  bun.lockb
  index.js
  lib/print.js
  package.json
  renovate.json
  tests/__snapshots__/index.test.ts.snap
  tests/data.js
  tests/index.js
  tests/index.test.ts
Labels: enhancement, size:XL

#108 feat: add groq ai
  README.md
  bin/fanyi.js
  bun.lockb
  index.js
  lib/config.js
  lib/print.js
  lib/source.json
  package.json
  tests/__snapshots__/index.test.ts.snap
  tests/index.test.ts
Labels: enhancement, size:L

#109 test: add more test cases
  tests/index.test.ts
Labels: enhancement, size:XS

#112 fix: ora is missing in deps
  package.json
Labels: bug, size:XS

#117 fix: ignore punycode module is deprecated warning in node 22
  bin/fanyi.js
Labels: bug, size:XS

#119 refactor: remove needle and xml2js, use node-fetch and fast-xml-parser
  bin/fanyi.js
  biome.json
  bun.lockb
  index.js
  package.json
Labels: enhancement, size:M

#120 feat: change model to llama-3.1-70b-versatile
  bun.lockb
  index.js
Labels: enhancement, size:XS

#123 chore: Update package.json
  package.json
Labels: korbit-code-analysis

#129 在shebang中添加-S标志修复env无法传递参数问题
  bin/fanyi.js
Labels: bug, korbit-code-analysis

#130 fix: iciba throw error when fy ant love
  lib/print.js
  tests/index.test.ts
Labels: bug, korbit-code-analysis

#135 refactor: refactor code by cursor
  lib/print.js
  lib/searchHistory.js
Labels: enhancement, size:S, korbit-code-analysis

#137 refactor: Migrate the whole project from cjs to esm
  .github/workflows/test.yml
  bin/fanyi.mjs
  bun.lockb
  index.mjs
  lib/config.mjs
  lib/iciba.mjs
  lib/searchHistory.mjs
  lib/utils.mjs
  package.json
  tests/index.test.ts
Labels: enhancement, size:L, gitauto, korbit-code-analysis
